import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    headerRow: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    headerCenter: {
      flex: 1,
      alignItems: "center",
    },
    backButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.surface1,
    },
    backButtonText: {
      color: colors.text1,
      fontWeight: "600",
    },
    title: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text1,
      textAlign: "center",
    },
    subtitle: {
      color: colors.text2,
      fontSize: 12,
      marginTop: 4,
      textAlign: "center",
    },
    count: {
      minWidth: 28,
      textAlign: "center",
      fontWeight: "700",
      color: colors.accent1,
    },
    content: {
      padding: 20,
      gap: 14,
      paddingBottom: 28,
    },
    loadingWrap: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    generatorCard: {
      backgroundColor: colors.surface1,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    sectionCard: {
      backgroundColor: colors.surface1,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    sectionTitle: {
      color: colors.text1,
      fontSize: 16,
      fontWeight: "700",
    },
    sectionBody: {
      color: colors.text2,
      fontSize: 13,
      lineHeight: 20,
    },
    sectionLink: {
      color: colors.accent1,
      fontWeight: "700",
      fontSize: 12,
    },
    toggleRow: {
      flexDirection: "row",
      gap: 10,
    },
    toggleChip: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
      borderRadius: 999,
      paddingVertical: 12,
      alignItems: "center",
    },
    toggleChipActive: {
      backgroundColor: colors.accent1,
      borderColor: colors.accent1,
    },
    toggleChipText: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 13,
    },
    toggleChipTextActive: {
      color: colors.bg,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
      color: colors.text1,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 14,
    },
    primaryButton: {
      backgroundColor: colors.accent1,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: "center",
    },
    secondaryButton: {
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: "center",
      flex: 1,
    },
    secondaryButtonText: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 14,
    },
    primaryButtonText: {
      color: colors.bg,
      fontWeight: "700",
      fontSize: 14,
    },
    disabledButton: {
      opacity: 0.6,
    },
    statsRow: {
      flexDirection: "row",
      gap: 10,
    },
    statCard: {
      flex: 1,
      backgroundColor: colors.surface1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 12,
    },
    statLabel: {
      color: colors.text2,
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      fontWeight: "700",
    },
    statValue: {
      color: colors.text1,
      fontSize: 22,
      fontWeight: "800",
      marginTop: 6,
    },
    statValueSmall: {
      color: colors.text1,
      fontSize: 14,
      fontWeight: "700",
      marginTop: 8,
      textTransform: "capitalize",
    },
    suggestionList: {
      gap: 8,
    },
    suggestionRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: colors.surface2,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    suggestionTitle: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 14,
    },
    suggestionMeta: {
      color: colors.text2,
      marginTop: 2,
      fontSize: 12,
    },
    suggestionAction: {
      color: colors.accent1,
      fontWeight: "700",
      fontSize: 12,
    },
    itemRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    itemMain: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface2,
    },
    checkboxActive: {
      backgroundColor: colors.accent1,
      borderColor: colors.accent1,
    },
    checkboxText: {
      color: colors.bg,
      fontWeight: "800",
      fontSize: 12,
    },
    itemTextWrap: {
      flex: 1,
    },
    itemName: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 14,
    },
    itemNameDone: {
      color: colors.text3,
      textDecorationLine: "line-through",
    },
    itemMeta: {
      color: colors.text2,
      fontSize: 12,
      marginTop: 4,
    },
    itemActions: {
      alignItems: "flex-end",
      gap: 6,
    },
    qtyPill: {
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    qtyPillText: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 12,
    },
    deleteText: {
      color: colors.danger,
      fontWeight: "700",
      fontSize: 12,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
      padding: 16,
    },
    modalCard: {
      backgroundColor: colors.bg,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      gap: 12,
    },
    modalTitle: {
      color: colors.text1,
      fontSize: 18,
      fontWeight: "800",
    },
    modalActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: 4,
    },
    chipRow: {
      gap: 10,
      paddingVertical: 4,
    },
    categoryChip: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    categoryChipActive: {
      backgroundColor: colors.accent1,
      borderColor: colors.accent1,
    },
    categoryChipText: {
      color: colors.text1,
      fontWeight: "700",
      fontSize: 12,
    },
    categoryChipTextActive: {
      color: colors.bg,
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 22,
    },
    emptyTitle: {
      color: colors.text1,
      fontSize: 18,
      fontWeight: "700",
      textAlign: "center",
    },
    emptyBody: {
      color: colors.text2,
      fontSize: 14,
      textAlign: "center",
    },
  });
